### ISSUE TITLE
syncing contacts with vdirsyncer does not work anymore

### ISSUE THREAD

**Issue by legrostdg** [jelmer/xandikos#40] opened 2017-03-21 13:51 UTC
Following https://github.com/pimutils/vdirsyncer/issues/605, I tried to set `collections = [["addressbook", null, "addressbook"]]` (note that `collections = null` used to work one week ago), this fails with:

    $ vdirsyncer -vdebug sync my_contacts
    debug: Using 1 maximal workers.
    Syncing my_contacts/addressbook
    debug: Loaded status for my_contacts/addressbook
    debug: PROPFIND http://localhost:8080/user/contacts/addressbook/
    debug: {'Depth': '1', 'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8'}
    debug: <?xml version="1.0" encoding="utf-8" ?>
    debug:             <D:propfind xmlns:D="DAV:">
    debug:                 <D:prop>
    debug:                     <D:resourcetype/>
    debug:                     <D:getcontenttype/>
    debug:                     <D:getetag/>
    debug:                 </D:prop>
    debug:             </D:propfind>
    debug:             
    debug: Sending request...
    debug: 207
    debug: {'Content-Type': 'text/xml; charset="utf-8"', 'Content-Length': '507'}
    debug: <ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:carddav"><ns0:response><ns0:href>/user/contacts/addressbook/</ns0:href><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /><ns1:addressbook /></ns0:resourcetype><ns0:getcontenttype>httpd/unix-directory</ns0:getcontenttype><ns0:getetag>"4b825dc642cb6eb9a060e54bf8d69288fbee4904"</ns0:getetag></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
    debug: Already normalized: '/user/contacts/addressbook/'
    debug: Skipping '/user/contacts/addressbook/', is collection.
    Copying (uploading) item ed0e2e72a72d08638d393e59ef322270e4e7b4050ce80f0cba97a17783f2f12c to my_contacts_remote/addressbook
    debug: Normalized URL from 'ed0e2e72a72d08638d393e59ef322270e4e7b4050ce80f0cba97a17783f2f12c.vcf' to '/user/contacts/addressbook/ed0e2e72a72d08638d393e59ef322270e4e7b4050ce80f0cba97a17783f2f12c.vcf'
    debug: PUT http://localhost:8080/user/contacts/addressbook/ed0e2e72a72d08638d393e59ef322270e4e7b4050ce80f0cba97a17783f2f12c.vcf
    debug: {'If-None-Match': '*', 'User-Agent': 'vdirsyncer', 'Content-Type': 'text/vcard'}
    debug: BEGIN:VCARD
    debug: VERSION:3.0
    debug: FN:Forest Gump
    debug: N:Gump;Forest
    debug: END:VCARD
    debug: Sending request...
    debug: 412
    debug: {'Content-Type': 'text/plain; encoding="utf-8"', 'Content-Length': '0'}
    
    error: Unknown error occured for my_contacts/addressbook: Precondition Failed
    error: Use `-vdebug` to see the full traceback.
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/cli/utils.py", line 74, in handle_cli_error
    debug:     raise e
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/sync.py", line 268, in sync
    debug:     action.run(a_info, b_info, conflict_resolution, partial_sync)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/sync.py", line 299, in run
    debug:     self._run_impl(a, b)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/sync.py", line 330, in _run_impl
    debug:     href, etag = self.dest.storage.upload(self.item)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/base.py", line 15, in inner
    debug:     return f(self, *args, **kwargs)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/base.py", line 15, in inner
    debug:     return f(self, *args, **kwargs)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 528, in upload
    debug:     return self._put(href, item, None)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 499, in _put
    debug:     headers=headers
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/storage/dav.py", line 358, in request
    debug:     return http.request(method, url, session=self._session, **more)
    debug:   File "/home/user/.local/lib/python3.5/site-packages/vdirsyncer-0.15.1.dev24+ng8a1e7a8-py3.5.egg/vdirsyncer/http.py", line 179, in request
    debug:     raise exceptions.PreconditionFailed(r.reason)
    error: 1 out of 2 tasks failed.

On xandikos' side I get:

    [pid: 14421|app: 0|req: 1/1] 127.0.0.1 (user) {38 vars in 529 bytes} [Tue Mar 21 14:51:03 2017] PROPFIND /user/contacts/addressbook/ => generated 507 bytes in 5 msecs (HTTP/1.1 207) 2 headers in 91 bytes (1 switches on core 0)
    [pid: 14421|app: 0|req: 2/2] 127.0.0.1 (user) {38 vars in 647 bytes} [Tue Mar 21 14:51:03 2017] PUT /user/contacts/addressbook/ed0e2e72a72d08638d393e59ef322270e4e7b4050ce80f0cba97a17783f2f12c.vcf => generated 0 bytes in 0 msecs (HTTP/1.1 412) 2 headers in 99 bytes (0 switches on core 0)

**Comment by untitaker** [comment] 2017-03-21 14:06
How did you create the collections, also please make sure to run the *very* latest version of xandikos (a potentially relevant PR #31 was merged two hours ago)

**Comment by jelmer** [comment] 2017-03-21 14:09
On the server side, does a file named
/user/contacts/addressbook/ed0e2e72a72d08638d393e59ef322270e4e7b4050ce80f0cba97a17783f2f12c.vcf
already exist before you run vdirsyncer?

**Comment by legrostdg** [comment] 2017-03-21 14:26
> How did you create the collections

With `xandikos --defaults -d /my_storage`

>  also please make sure to run the very latest version of xandikos (a potentially relevant PR #31 was merged two hours ago)

I tried this, same error.

> On the server side, does a file named /user/contacts/addressbook/ed0e2e72a72d08638d393e59ef322270e4e7b4050ce80f0cba97a17783f2f12c.vcf already exist before you run vdirsyncer?

`/user/contacts/addressbook` is empty before and after running vdirsyncer (except from the `.git` dir)

**Comment by legrostdg** [comment] 2017-03-21 18:13
I'm trying to find the commit which introduced the issue.
1e009f1a30 does not work
5f6e3ef798 does work

**Comment by untitaker** [comment] 2017-03-21 18:16
If you use a different collection name within the vdirsyncer config, vdirsyncer should be able to create that new collection and correctly use it.

**Comment by legrostdg** [comment] 2017-03-21 18:32
I don't think the problem is with the collection name. I get "error: Unknown error occured for my_contacts/addressbook: Precondition Failed" with 1e009f1 and fbae24d038, but not with 53e6e7d9d1 and 5f6e3ef

**Comment by legrostdg** [comment] 2017-03-21 18:34
(I have no problem with creating the collection)

**Comment by legrostdg** [comment] 2017-03-21 18:38
The problem seems to appear with d41a769c1c

**Comment by legrostdg** [comment] 2017-03-21 18:45
commenting `store.load_extra_file_handler(VCardFile)` in xandikos/web.py on master fixes the issue... Hope that helps in fixing both vdirsyncer (for the error message) and xandikos :-).

**Comment by legrostdg** [comment] 2017-03-21 18:46
The only vcard I provided is pretty simple:
  
    BEGIN:VCARD
    VERSION:3.0
    FN:Forest Gump
    N:Gump;Forest
    END:VCARD

**Comment by untitaker** [comment] 2017-03-21 18:56
Please pastebin the exact file, bit for bit (a normal pastebin will do) I think I know what the issue is though.

**Comment by legrostdg** [comment] 2017-03-21 18:58
http://pastebin.com/DD0MCSsX

**Comment by untitaker** [comment] 2017-03-21 19:46
Please use a different pastebin. That one is known for "normalizing" newlines.

On 21 March 2017 19:58:59 CET, legrostdg <notifications@github.com> wrote:
>http://pastebin.com/DD0MCSsX
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/xandikos/issues/40#issuecomment-288183862

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment] 2017-03-21 19:54
Particularly I'd like to know whether the file has a trailing newline.

**Comment by legrostdg** [comment] 2017-03-21 21:24
@untitaker https://framadrop.org/r/4Z03PN6XdT#gW7tGen1+UMV+ntR53SUb1JbnqgxlmkBGpeXdoM3zZk=

**Comment by untitaker** [comment] 2017-03-21 21:27
ok, please try out #41

**Comment by legrostdg** [comment] 2017-03-21 22:54
It works. Thanks!

It would be nice to improve the error message on vdirsyncer's side, and issue a warning if a vcard does not validate on xandikos' side.

**Comment by jelmer** [comment] 2017-03-21 23:15
The error element in the status returned to vdirsyncer should give it a clue why a precondition failed.

I'm also changing Xandikos to include the description element, with a human-readable error message.

**Comment by untitaker** [comment] 2017-03-21 23:30
According to the debug log in the OP there is no response content for a PUT with malformed payload.

**Comment by jelmer** [comment] 2017-03-26 15:15
Ah, yeah. The right error was raised within Xandikos but not actually included in the HTTP reply.

As of b7128a2edbeb5e57791d1553fa7d86f4def47932 and 32bfe49493e171f08e2281d3fb452a0a3432bf7e the error description should now be included.

**Closed by jelmer** 2017-03-26 15:15 UTC
Labels: bug
